version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: travel_flight_api
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  celery_worker:
    build:
      context: .
      dockerfile: celery.Dockerfile
    container_name: travel_flight_celery
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
    command: ["celery", "-A", "app.tasks.celery_app", "worker", "--loglevel=info"]

  redis:
    image: redis:7.2-alpine
    container_name: travel_flight_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
