version: "3.9"
services:
  api:
    build:               
      context: .
      dockerfile: app.Dockerfile
    ports: ["8000:8000"]
    env_file: [.env]
    depends_on: [tools, redis]
  
  tools:                 
    build:
      context: .
      dockerfile: tools_server/Dockerfile
    container_name: flight_tool_server
    ports: ["7000:7000"] 
    env_file: [.env]
    depends_on: [redis]   

  celery_worker:         
    build:
      context: .
      dockerfile: celery.Dockerfile
    depends_on: [redis]
    env_file: [.env]

  redis:
    image: redis:7.2-alpine
    container_name: travel_flight_redis
    ports: ["6379:6379"]
